#!/usr/bin/perl -w

use strict;

my ($WORKSPACE, $SCHEME) = @ARGV;

my $buildSettings = qx{xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showBuildSettings};

my @args = ("-workspace", $WORKSPACE, "-scheme", $SCHEME, "test", "CODE_SIGNING_REQUIRED=NO", "CODE_SIGN_IDENTITY=");

unshift @args, "-sdk", "iphonesimulator" if $buildSettings =~ /\bPLATFORM_NAME = iphoneos/i;

print "xctool @args\n";
exec("xctool", @args);

